/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mdy.dzs.net;

import com.mdy.dzs.data.DataApplication;
import com.mdy.dzs.game.SystemApplication;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import io.netty.bootstrap.ServerBootstrap;
import io.netty.channel.Channel;
import io.netty.channel.EventLoopGroup;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.nio.NioServerSocketChannel;
import io.netty.handler.logging.LogLevel;
import io.netty.handler.logging.LoggingHandler;

public class WebSocketServer {
    static final Logger logger = LogManager.getLogger(WebSocketServer.class);
    static final int PORT = 8080;

    public static void main(String[] args) {
        DataApplication.Instance().startUp();
        SystemApplication.Instance().startUp();
        SystemApplication.Instance().cacheManager().reloadActivity();

        EventLoopGroup bossGroup = new NioEventLoopGroup(1);
        EventLoopGroup workerGroup = new NioEventLoopGroup();

        try {
            ServerBootstrap b = new ServerBootstrap();
            b.group(bossGroup, workerGroup).channel(NioServerSocketChannel.class)
                    .handler(new LoggingHandler(LogLevel.INFO)).childHandler(new WebSocketServerInitializer());

            Channel ch = b.bind(PORT).sync().channel();

            logger.info("Open your web browser and navigate to " + "127.0.0.1:" + PORT);
            ch.closeFuture().sync();
        } catch (InterruptedException e) {
            e.printStackTrace();
        } finally {
            bossGroup.shutdownGracefully();
            workerGroup.shutdownGracefully();
        }
    }
}
